# Generated by Django 3.1.14 on 2022-10-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20221005_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='default title'),
            preserve_default=False,
        ),
    ]
